# Author
author:
  name:         Henri Bredt
  email:        hello@henribredt.de
  twitter:      henricreates

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate:       5
permalink:      /:year-:month-:day/:title

# Site settings

title:          Henri Bredt Â· Words;
navbartitle:    Words;
baseurl:        "/blog"
url:            "https://henribredt.de"